package gatech.edu.STIECR.controller;

import java.util.regex.Pattern;

import gatech.edu.STIECR.JSON.CodeableConcept;

public class ControllerUtils {
	public static String LIST_CONCAT_STRING = ", ";
	
	public static final CodeableConcept[] CT1D = {
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis infection (disorder)", "240589008"),
			new CodeableConcept("SNOMED CT", "Acute genitourinary Chlamydia trachomatis infection (disorder)", "426247003"),
			new CodeableConcept("SNOMED CT", "Perihepatitis due to Chlamydia trachomatis (disorder)", "143511000119105"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis infection in mother complicating childbirth (disorder)", "10750051000119105"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis infection of anus and rectum (disorder)", "420910002"),
			new CodeableConcept("SNOMED CT", "Infection of anus due to Chlamydia trachomatis (disorder)", "446642005"),
			new CodeableConcept("SNOMED CT", "Infection of rectum due to Chlamydia trachomatis (disorder)", "447372001"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis infection of genital structure (disorder)", "428015005"),
			new CodeableConcept("SNOMED CT", "Infection of cervix due to Chlamydia trachomatis (disorder)", "447353001"),
			new CodeableConcept("SNOMED CT", "Infection of epididymis due to Chlamydia trachomatis (disorder)", "446471004"),
			new CodeableConcept("SNOMED CT", "Infection of testis due to Chlamydia trachomatis (disorder)", "446902002"),
			new CodeableConcept("SNOMED CT", "Infection of vagina due to Chlamydia trachomatis (disorder)", "447402003"),
			new CodeableConcept("SNOMED CT", "Infection of peritoneum due to Chlamydia trachomatis (disorder)", "446752000"),
			new CodeableConcept("SNOMED CT", "Female chlamydial pelvic inflammatory disease (disorder)", "198176005"),
			new CodeableConcept("SNOMED CT", "Infection of pharynx due to Chlamydia trachomatis (disorder)", "446594000"),
			new CodeableConcept("SNOMED CT", "Infection of vulva due to Chlamydia trachomatis (disorder)", "447386002"),
			new CodeableConcept("SNOMED CT", "Neonatal chlamydial conjunctivitis (disorder)", "240591000"),
			new CodeableConcept("SNOMED CT", "Urethritis due to Chlamydia trachomatis (disorder)", "179101003"),
			new CodeableConcept("SNOMED CT", "Venereal disease due to Chlamydia trachomatis (disorder)", "112121000119105"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis infection in pregnancy (disorder)", "1621000119101"),
			new CodeableConcept("SNOMED CT", "Inclusion conjunctivitis of the adult (disorder)", "56009001"),
			new CodeableConcept("SNOMED CT", "Pelvic inflammatory disease with female sterility due to Chlamydia trachomatis (disorder)", "367504009"),
			new CodeableConcept("ICD10CM", "Chlamydial lymphogranuloma (venereum)", "A55"),
			new CodeableConcept("ICD10CM", "Chlamydial infection of lower genitourinary tract, unspecified", "A56.00"),
			new CodeableConcept("ICD10CM", "Chlamydial cystitis and urethritis", "A56.01"),
			new CodeableConcept("ICD10CM", "Chlamydial vulvovaginitis", "A56.02"),
			new CodeableConcept("ICD10CM", "Other chlamydial infection of lower genitourinary tract", "A56.09"),
			new CodeableConcept("ICD10CM", "Chlamydial female pelvic inflammatory disease", "A56.11"),
			new CodeableConcept("ICD10CM", "Other chlamydial genitourinary infection", "A56.19"),
			new CodeableConcept("ICD10CM", "Chlamydial infection of genitourinary tract, unspecified", "A56.2"),
			new CodeableConcept("ICD10CM", "Chlamydial infection of anus and rectum", "A56.3"),
			new CodeableConcept("ICD10CM", "Chlamydial infection of pharynx", "A56.4"),
			new CodeableConcept("ICD10CM", "Sexually transmitted chlamydial infection of other sites", "A56.8"),
			new CodeableConcept("ICD10CM", "Initial stage of trachoma", "A71.0"),
			new CodeableConcept("ICD10CM", "Active stage of trachoma", "A71.1"),
			new CodeableConcept("ICD10CM", "Trachoma, unspecified", "A71.9"),
			new CodeableConcept("ICD10CM", "Chlamydial conjunctivitis", "A74.0"),
			new CodeableConcept("ICD10CM", "Chlamydial peritonitis", "A74.81"),
			new CodeableConcept("ICD10CM", "Other chlamydial diseases", "A74.89"),
			new CodeableConcept("ICD10CM", "Chlamydial infection, unspecified", "A74.9"),
			new CodeableConcept("ICD10CM", "Congenital pneumonia due to Chlamydia", "P23.1"),
			new CodeableConcept("ICD10CM", "Chlamydial pneumonia", "J16.0"),
	};
	public static final CodeableConcept[] CT1R = {
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis (organism)", "63938009"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype A (organism)", "115289001"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype B (organism)", "115290005"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype Ba (organism)", "115291009"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype C (organism)", "115292002"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype D (organism)", "115293007"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype E (organism)", "115294001"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype F (organism)", "115295000"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype G (organism)", "115319008"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype H (organism)", "115328009"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype I (organism)", "115296004"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype J (organism)", "115297008"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype Ja (organism)", "442505006"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype K (organism)", "115298003"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype L (organism)", "115299006"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype L1 (organism)", "115300003"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype L2 (organism)", "115301004"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis, serotype L3 (organism)", "115318000"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis deoxyribonucleic acid (substance)", "121181000"),
			new CodeableConcept("SNOMED CT", "Deoxyribonucleic acid of Chlamydia trachomatis L2 (substance)", "708219005"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis ribosomal ribonucleic acid (substance)", "121106008"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis antigen (substance)", "121002007"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis F antigen (substance)", "121015003"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis G antigen (substance)", "121016002"),
			new CodeableConcept("SNOMED CT", "Chlamydia trachomatis K antigen (substance)", "121017006")
			
	};
	public static final CodeableConcept[] CT2L = {
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Vaginal fluid by Organism specific culture", "14464-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Vaginal fluid by Immunofluorescence", "14510-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Cervix by Organism specific culture", "14463-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Urethra by Organism specific culture", "14465-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Urine sediment by Organism specific culture", "14467-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Genital specimen by Organism specific culture", "45095-7"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Unspecified specimen by Organism specific culture", "6349-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Blood by Organism specific culture", "14461-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Cerebral spinal fluid by Organism specific culture", "14462-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Anal by Organism specific culture", "45093-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Conjunctival specimen by Organism specific culture", "45094-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis [Presence] in Nasopharynx by Organism specific culture", "45096-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Cervix by Immunofluorescence", "14509-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Urethra by Immunofluorescence", "14511-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Urine sediment by Immunofluorescence", "14513-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Stool by Immunofluorescence", "6352-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Unspecified specimen by Immunofluorescence", "6355-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Conjunctival specimen by Immunofluorescence", "6351-1"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Unspecified specimen by Immunofluorescence", "6355-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Cervix by Immunoassay", "14470-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Vaginal fluid by Immunoassay", "14471-7"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Urethra by Immunoassay", "14472-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Urine sediment by Immunoassay", "14474-1"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Unspecified specimen by Immunoassay", "6354-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Conjunctival specimen by Immunoassay", "6350-3"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis Ag [Presence] in Nasopharynx by Immunoassay", "45092-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Genital specimen by DNA probe", "16600-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urine by DNA probe", "16601-7"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urethra by DNA probe", "21192-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Genital fluid by DNA probe", "23838-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Cervix by DNA probe", "45067-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Genital specimen by DNA probe", "45069-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Vaginal fluid by DNA probe", "45070-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Urine by DNA probe", "45074-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Urethra by DNA probe", "45075-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen by DNA probe", "45076-7"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Cervix by DNA probe", "45078-3"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Vaginal fluid by DNA probe", "45080-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen by DNA probe", "4993-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Conjunctival specimen by DNA probe", "21188-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Anal by DNA probe", "45072-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Nasopharynx by DNA probe", "45085-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Anal by DNA probe", "45089-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urine by Probe and target amplification method", "42931-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen by Probe and target amplification method", "43304-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "47362-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Cervix by Probe and target amplification method", "50387-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "50411-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urethra by Probe and target amplification method", "53925-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Vaginal fluid by Probe and target amplification method", "53926-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Anal by Probe and target amplification method", "57287-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Nasopharynx by Probe and target amplification method", "57288-3"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Conjunctival specimen by Probe and target amplification method", "21187-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Cervical mucus by Probe and target amplification method", "21189-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Cervix by Probe and target amplification method", "21190-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Urethra by Probe and target amplification method", "21191-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Unspecified specimen by Probe and target amplification method", "21613-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and target amplification method", "36902-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urine by Probe and target amplification method", "42931-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen by Probe and target amplification method", "43304-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Anal by DNA probe", "45072-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Nasopharynx by DNA probe", "45085-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Anal by DNA probe", "45089-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urine by Probe and target amplification method", "42931-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen by Probe and target amplification method", "43304-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "47362-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Cervix by Probe and target amplification method", "50387-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "50411-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urethra by Probe and target amplification method", "53925-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Vaginal fluid by Probe and target amplification method", "53926-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Anal by Probe and target amplification method", "57287-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Nasopharynx by Probe and target amplification method", "57288-3"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Conjunctival specimen by Probe and target amplification method", "21187-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Cervical mucus by Probe and target amplification method", "21189-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Cervix by Probe and target amplification method", "21190-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Urethra by Probe and target amplification method", "21191-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Unspecified specimen by Probe and target amplification method", "21613-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and target amplification method", "36902-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urine by Probe and target amplification method", "42931-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen by Probe and target amplification method", "43304-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Urine by Probe and target amplification method", "44806-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Genital specimen by Probe and target amplification method", "44807-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Cervix by Probe and target amplification method", "45068-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Vaginal fluid by Probe and target amplification method", "45084-1"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Nasopharynx by Probe and target amplification method", "45086-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Anal by Probe and target amplification method", "45090-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis L2 DNA [Presence] in Unspecified specimen by Probe and target amplification method", "47211-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "47362-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "50311-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Cervix by Probe and target amplification method", "50387-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "50411-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Semen by Probe and target amplification method", "51578-3"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Urethra by Probe and target amplification method", "53925-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Vaginal fluid by Probe and target amplification method", "53926-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Anal by Probe and target amplification method", "57287-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis rRNA [Presence] in Nasopharynx by Probe and target amplification method", "57288-3"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis DNA [Presence] in Genital specimen by Probe and target amplification method", "6356-0"),
	};
	
	public static final CodeableConcept[] CT2R = {
			new CodeableConcept("SNOMED CT", "Yes (qualifier value)", "373066001"),
			new CodeableConcept("SNOMED CT", "Present ++ out of ++++ (qualifier value)", "260348001"),
			new CodeableConcept("SNOMED CT", "Abnormal presence of (qualifier value)", "43261007"),
			new CodeableConcept("SNOMED CT", "Present two plus out of three plus (qualifier value)", "441517005"),
			new CodeableConcept("SNOMED CT", "Present (qualifier value)", "52101004"),
			new CodeableConcept("SNOMED CT", "Present ++++ out of ++++ (qualifier value)", "260350009"),
			new CodeableConcept("SNOMED CT", "Just noticeable (qualifier value)", "260351008"),
			new CodeableConcept("SNOMED CT", "Presence findings (qualifier value)", "260411009"),
			new CodeableConcept("SNOMED CT", "Present one plus out of three plus (qualifier value)", "441614007"),
			new CodeableConcept("SNOMED CT", "Positive (qualifier value)", "10828004"),
			new CodeableConcept("SNOMED CT", "Present + out of ++++ (qualifier value)", "260347006"),
			new CodeableConcept("SNOMED CT", "Weakly positive (qualifier value)", "260408008"),
			new CodeableConcept("SNOMED CT", "Present +++ out of ++++ (qualifier value)", "260349009"),
			new CodeableConcept("SNOMED CT", "Trace (qualifier value)", "260405006"),
			new CodeableConcept("SNOMED CT", "Isolated (qualifier value)", "46651001"),
			new CodeableConcept("SNOMED CT", "Present three plus out of three plus (qualifier value)", "441521003"),
			new CodeableConcept("SNOMED CT", "Detected (qualifier value)", "260373001"),
			new CodeableConcept("SNOMED CT", "Presence of infection (qualifier value)", "260976002"),
	};
	
	public static final CodeableConcept[] GC1D = {
			new CodeableConcept("SNOMED CT", "Gonorrhea (disorder)", "15628003"),
			new CodeableConcept("SNOMED CT", "Abscess gonococcal (disorder)", "235861001"),
			new CodeableConcept("SNOMED CT", "Gonococcal Bartholin's gland abscess (disorder)", "240573005"),
			new CodeableConcept("SNOMED CT", "Gonococcal urethral abscess (disorder)", "236687008"),
			new CodeableConcept("SNOMED CT", "Abscess of urethral gland due to Neisseria gonorrhoeae (disorder)", "444834005"),
			new CodeableConcept("SNOMED CT", "Gonococcal Littré gland abscess (disorder)", "240578001"),
			new CodeableConcept("SNOMED CT", "Acute gonorrhea of genitourinary tract (disorder)", "17305005"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal epididymo-orchitis (disorder)", "30168008"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal prostatitis (disorder)", "111806005"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal seminal vesiculitis (disorder)", "65049003"),
			new CodeableConcept("SNOMED CT", "Acute gonorrhea of lower genitourinary tract (disorder)", "54825009"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal bartholinitis (disorder)", "80604007"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal cervicitis (disorder)", "20943002"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal cystitis (disorder)", "24868007"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal urethritis (disorder", "29864006"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal vulvovaginitis (disorder)", "2390000"),
			new CodeableConcept("SNOMED CT", "Acute gonorrhea of upper genitourinary tract (disorder)", "50970007"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal endometritis (disorder)", "65295003"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal salpingitis (disorder)", "45377007"),
			new CodeableConcept("SNOMED CT", "Chronic gonorrhea (disorder)", "27681008"),
			new CodeableConcept("SNOMED CT", "Chronic gonorrhea of genitourinary tract (disorder", "28572009"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal epididymo-orchitis (disorder)", "35526001"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal prostatitis (disorder)", "60893000"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal seminal vesiculitis (disorder)", "23975003"),
			new CodeableConcept("SNOMED CT", "Chronic gonorrhea lower genitourinary tract (disorder)", "186915005"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal bartholinitis (disorder)", "12373006"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal cervicitis (disorder)", "76802005"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal cystitis (disorder)", "88813005"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal urethritis (disorder)", "44412000"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal vulvovaginitis (disorder)", "11906007"),
			new CodeableConcept("SNOMED CT", "Chronic gonorrhea of upper genitourinary tract (disorder)", "80388004"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal endometritis (disorder)", "31999004"),
			new CodeableConcept("SNOMED CT", "Chronic gonococcal salpingitis (disorder)", "53529004"),
			new CodeableConcept("SNOMED CT", "Gonococcal anal infection (disorder)", "186931002"),
			new CodeableConcept("SNOMED CT", "Gonococcal bursitis (disorder)", "46699001"),
			new CodeableConcept("SNOMED CT", "Gonococcal cellulitis (disorder)", "240584003"),
			new CodeableConcept("SNOMED CT", "Gonococcal Cowperitis (disorder)", "240576002"),
			new CodeableConcept("SNOMED CT", "Gonococcal cystitis (disorder", "197848003"),
			new CodeableConcept("SNOMED CT", "Gonococcal epididymitis (disorder)", "236766009"),
			new CodeableConcept("SNOMED CT", "Gonococcal epididymo-orchitis (disorder)", "236772009"),
			new CodeableConcept("SNOMED CT", "Gonococcal female pelvic infection (disorder)", "240581006"),
			new CodeableConcept("SNOMED CT", "Gonococcal cervicitis (disorder)", "237083000"),
			new CodeableConcept("SNOMED CT", "Gonococcal endometritis (disorder)", "237069002"),
			new CodeableConcept("SNOMED CT", "Gonococcal paraurethral gland abscess (disorder)", "240579009"),
			new CodeableConcept("SNOMED CT", "Gonococcal salpingitis (disorder)", "237038001"),
			new CodeableConcept("SNOMED CT", "Gonococcal Skenitis (disorder)", "240574004"),
			new CodeableConcept("SNOMED CT", "Gonococcal tubo-ovarian abscess (disorder)", "237046000"),
			new CodeableConcept("SNOMED CT", "Gonococcal vulvovaginitis (disorder)", "237095000"),
			new CodeableConcept("SNOMED CT", "Neonatal gonococcal vulvovaginitis (disorder)", "237096004"),
			new CodeableConcept("SNOMED CT", "Gonococcal heart disease (disorder)", "9241004"),
			new CodeableConcept("SNOMED CT", "Gonococcal endocarditis (disorder)", "61048000"),
			new CodeableConcept("SNOMED CT", "Gonococcal hepatitis (disorder)", "235863003"),
			new CodeableConcept("SNOMED CT", "Gonococcal infection of eye (disorder)", "35876006"),
			new CodeableConcept("SNOMED CT", "Gonococcal conjunctivitis (disorder)", "231858009"),
			new CodeableConcept("SNOMED CT", "Gonococcal conjunctivitis neonatorum (disorder)", "28438004"),
			new CodeableConcept("SNOMED CT", "Gonococcal endophthalmia (disorder)", "111807001"),
			new CodeableConcept("SNOMED CT", "Gonococcal iritis (disorder)", "342381000119109"),
			new CodeableConcept("SNOMED CT", "Gonococcal iridocyclitis (disorder)", "9091006"),
			new CodeableConcept("SNOMED CT", "Gonococcal keratitis (disorder)", "40149008"),
			new CodeableConcept("SNOMED CT", "Gonococcal infection of joint (disorder)", "44743006"),
			new CodeableConcept("SNOMED CT", "Gonococcal infection of the central nervous system (disorder)", "406581000"),
			new CodeableConcept("SNOMED CT", "Gonococcal meningitis (disorder)", "151004"),
			new CodeableConcept("SNOMED CT", "Gonococcal keratosis (disorder)", "60335002"),
			new CodeableConcept("SNOMED CT", "Gonococcal Littritis (disorder)", "240577006"),
			new CodeableConcept("SNOMED CT", "Gonococcal lymphangitis of penis (disorder)", "238419002"),
			new CodeableConcept("SNOMED CT", "Gonococcal pericarditis (disorder)", "90428001"),
			new CodeableConcept("SNOMED CT", "Acute gonococcal pericarditis (disorder)", "194910001"),
			new CodeableConcept("SNOMED CT", "Gonococcal perihepatitis (disorder)", "237042003"),
			new CodeableConcept("SNOMED CT", "Gonococcal peritonitis (disorder)", "186939000"),
			new CodeableConcept("SNOMED CT", "Gonococcal pelvic peritonitis (disorder)", "307423008"),
			new CodeableConcept("SNOMED CT", "Gonococcal pneumonia (disorder)", "1087061000119106"),
			new CodeableConcept("SNOMED CT", "Gonococcal prostatitis (disorder)", "197967000"),
			new CodeableConcept("SNOMED CT", "Gonococcal seminal vesiculitis (disorder)", "301990003"),
			new CodeableConcept("SNOMED CT", "Gonococcal spondylitis (disorder)", "53664003"),
			new CodeableConcept("SNOMED CT", "Gonococcal synovitis or tenosynovitis (disorder)", "266138002"),
			new CodeableConcept("SNOMED CT", "Gonococcal synovitis (disorder)", "240582004"),
			new CodeableConcept("SNOMED CT", "Gonococcal tenosynovitis (disorder)", "240039005"),
			new CodeableConcept("SNOMED CT", "Gonococcal Tysonitis (disorder)", "240575003"),
			new CodeableConcept("SNOMED CT", "Gonococcal urethritis (disorder)", "236682002"),
			new CodeableConcept("SNOMED CT", "Gonococcemia (disorder)", "5085001"),
			new CodeableConcept("SNOMED CT", "Gonococcal arthritis dermatitis syndrome (disorder)", "272006008"),
			new CodeableConcept("SNOMED CT", "Gonorrhea of pharynx (disorder)", "74372003"),
			new CodeableConcept("SNOMED CT", "Gonorrhea of rectum (disorder)", "42746002"),
			new CodeableConcept("SNOMED CT", "Gonococcal rectal infection (disorder)", "186932009"),
			new CodeableConcept("SNOMED CT", "Gonorrhea with local complication (disorder)", "240572000"),
			new CodeableConcept("SNOMED CT", "Maternal gonorrhea during pregnancy, childbirth and the puerperium (disorder)", "199161008"),
			new CodeableConcept("SNOMED CT", "Gonorrhea in mother complicating pregnancy, childbirth AND/OR puerperium (disorder)", "35255008"),
			new CodeableConcept("SNOMED CT", "Gonorrhea in mother complicating childbirth (disorder)", "10754031000119105"),
			new CodeableConcept("SNOMED CT", "Maternal gonorrhea during pregnancy - baby delivered (disorder)", "199163006"),
			new CodeableConcept("SNOMED CT", "Maternal gonorrhea during pregnancy - baby not yet delivered (disorder)", "199165004"),
			new CodeableConcept("SNOMED CT", "Maternal gonorrhea in the puerperium - baby delivered during current episode of care (disorder)", "199164000"),
			new CodeableConcept("SNOMED CT", "Maternal gonorrhea in the puerperium - baby delivered during previous episode of care (disorder)", "199166003"),
			new CodeableConcept("SNOMED CT", "Neonatal gonococcal infection (disorder)", "240571007"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of lower genitourinary tract, unspecified", "A54.00"),
			new CodeableConcept("ICD10CM", "Gonococcal cystitis and urethritis, unspecified", "A54.01"),
			new CodeableConcept("ICD10CM", "Gonococcal vulvovaginitis, unspecified", "A54.02"),
			new CodeableConcept("ICD10CM", "Gonococcal cervicitis, unspecified", "A54.03"),
			new CodeableConcept("ICD10CM", "Other gonococcal infection of lower genitourinary tract", "A54.09"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of lower genitourinary tract with periurethral and accessory gland abscess", "A54.1"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of kidney and ureter", "A54.21"),
			new CodeableConcept("ICD10CM", "Gonococcal prostatitis", "A54.22"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of other male genital organs", "A54.23"),
			new CodeableConcept("ICD10CM", "Gonococcal female pelvic inflammatory disease", "A54.24"),
			new CodeableConcept("ICD10CM", "Other gonococcal genitourinary infections", "A54.29"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of eye, unspecified", "A54.30"),
			new CodeableConcept("ICD10CM", "Gonococcal conjunctivitis", "A54.31"),
			new CodeableConcept("ICD10CM", "Gonococcal iridocyclitis", "A54.32"),
			new CodeableConcept("ICD10CM", "Gonococcal keratitis", "A54.33"),
			new CodeableConcept("ICD10CM", "Other gonococcal eye infection", "A54.39"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of musculoskeletal system, unspecified", "A54.40"),
			new CodeableConcept("ICD10CM", "Gonococcal spondylopathy", "A54.41"),
			new CodeableConcept("ICD10CM", "Gonococcal arthritis", "A54.42"),
			new CodeableConcept("ICD10CM", "Gonococcal osteomyelitis", "A54.43"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of other musculoskeletal tissue", "A54.49"),
			new CodeableConcept("ICD10CM", "Gonococcal pharyngitis", "A54.5"),
			new CodeableConcept("ICD10CM", "Gonococcal infection of anus and rectum", "A54.6"),
			new CodeableConcept("ICD10CM", "Gonococcal meningitis", "A54.81"),
			new CodeableConcept("ICD10CM", "Gonococcal brain abscess", "A54.82"),
			new CodeableConcept("ICD10CM", "Gonococcal heart infection", "A54.83"),
			new CodeableConcept("ICD10CM", "Gonococcal pneumonia", "A54.84"),
			new CodeableConcept("ICD10CM", "Gonococcal peritonitis", "A54.85"),
			new CodeableConcept("ICD10CM", "Gonococcal sepsis", "A54.86"),
			new CodeableConcept("ICD10CM", "Other gonococcal infections", "A54.89"),
			new CodeableConcept("ICD10CM", "Gonococcal infection, unspecified", "A54.9"),
			new CodeableConcept("ICD10CM", "Gonorrhea complicating pregnancy, first trimester", "O98.211"),
			new CodeableConcept("ICD10CM", "Gonorrhea complicating pregnancy, second trimester", "O98.212"),
			new CodeableConcept("ICD10CM", "Gonorrhea complicating pregnancy, third trimester", "O98.213"),
			new CodeableConcept("ICD10CM", "Gonorrhea complicating pregnancy, unspecified trimester", "O98.219"),
			new CodeableConcept("ICD10CM", "Gonorrhea complicating childbirth", "O98.22"),
			new CodeableConcept("ICD10CM", "Gonorrhea complicating the puerperium", "O98.23"),
	};
	
	public static final CodeableConcept[] GC1R = {
			new CodeableConcept("SNOMED CT", "Neisseria gonorrhoeae (organism)", "68704007"),
			new CodeableConcept("SNOMED CT", "Neisseria gonorrhoeae, beta lactamase negative (organism)", "414809001"),
			new CodeableConcept("SNOMED CT", "Gram-negative diplococcus (organism)", "83410001"),
			new CodeableConcept("SNOMED CT", "Cephalosporin-resistant Neisseria gonorrhoeae (organism)", "277503000"),
			new CodeableConcept("SNOMED CT", "Fluoroquinolone-resistant Neisseria gonorrhoeae (organism)", "409805000"),
			new CodeableConcept("SNOMED CT", "Penicillinase-producing Neisseria gonorrhoeae (organism)", "277501003"),
			new CodeableConcept("SNOMED CT", "Spectinomycin-resistant Neisseria gonorrhoeae (organism)", "277504006"),
			new CodeableConcept("SNOMED CT", "Tetracycline-resistant Neisseria gonorrhoeae (organism)", "277502005"),
			new CodeableConcept("SNOMED CT", "Neisseria gonorrhoeae deoxyribonucleic acid (substance)", "703483000"),
			new CodeableConcept("SNOMED CT", "Neisseria gonorrhoeae ribosomal ribonucleic acid (substance)", "121172006"),
			new CodeableConcept("SNOMED CT", "Neisseria gonorrhoeae antigen (substance)", "120977006")
	};
	
	public static final CodeableConcept[] GC2L = {
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Cervix by Organism specific culture", "688-2"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Genital specimen by Organism specific culture", "691-6"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Anal by Organism specific culture", "14127-5"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Conjunctival specimen by Organism specific culture", "30099-6"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Endometrium by Organism specific culture", "690-8"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Genital lochia by Organism specific culture", "692-4"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Vaginal fluid by Organism specific culture", "693-2"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Semen by Organism specific culture", "694-0"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Synovial fluid by Organism", "695-7"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Throat by Organism specific culture", "696-5"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Urethra by Organism specific culture", "697-3"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae [Presence] in Unspecified specimen by Organism specific culture", "698-1"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Cervical mucus by Probe and target amplification method", "21414-8"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Urethra by Probe and target amplification method", "21415-5"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Urine by Probe and target amplification method", "21416-3"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and target amplification method", "24111-7"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae rRNA [Presence] in Cervix by DNA probe", "32198-4"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae rRNA [Presence] in Urethra by DNA probe", "32199-2"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Vaginal fluid by Probe and target amplification method", "32705-6"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae rRNA [Presence] in Conjunctival specimen by DNA probe", "33904-4"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Conjunctival specimen by Probe and target amplification method", "35735-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and target amplification method", "36902-5"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen by Probe and target amplification method", "43305-2"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and signal amplification method", "43403-5"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and signal amplification method", "43406-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Urine by Probe and target amplification method", "44806-8"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Genital specimen by Probe and target amplification method", "44807-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Cervix by DNA probe", "45067-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Cervix by Probe and target amplification method", "45068-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Genital specimen by DNA probe", "45069-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Vaginal fluid by DNA probe", "45070-0"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Anal by DNA probe", "45072-6"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Tissue by DNA probe", "45073-4"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Urine by DNA probe", "45074-2"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Urethra by DNA probe", "45075-9"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen by DNA probe", "45076-7"),
			new CodeableConcept("LOINC", "Chlamydia trachomatis+Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "47362-9"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Genital specimen by Probe and target amplification method", "47387-6"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen by DNA probe", "5028-6"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "50326-8"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae rRNA [Presence] in Cervix by Probe and target amplification method", "50388-8"),
			new CodeableConcept("LOINC", "Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen from donor by Probe and target amplification method", "50412-6"),
	};
	public static final CodeableConcept[] STIMed = {
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 100 MG Oral Capsule Clinical Drug", "1649990"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 100 MG Oral Capsule Clinical Drug", "1649988"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 75 MG Oral Tablet   Clinical Drug", "1649429"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 75 MG Oral Tablet   Clinical Drug", "1649425"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 50 MG Oral Capsule  Clinical Drug", "1649405"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 50 MG Oral Capsule  Clinical Drug", "1649401"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 50 MG Delayed Release Oral Tablet   Clinical Drug", "1653433"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 50 MG Oral Tablet   Clinical Drug", "1652674"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 50 MG Oral Tablet   Clinical Drug", "1652673"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 150 MG Oral Tablet  Clinical Drug", "1650446"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 150 MG Oral Tablet  Clinical Drug", "1650444"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 100 MG Oral Tablet  Clinical Drug", "1650143"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 100 MG Oral Tablet  Clinical Drug", "1650142"),
			new CodeableConcept("RxNorm", "Doxycycline Calcium 5 MG/ML Oral Suspension Clinical Drug", "1650032"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 5 MG/ML Oral Suspension Clinical Drug", "1650030"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 200 MG Delayed Release Oral Tablet  Clinical Drug", "1423080"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 75 MG Oral Capsule  Clinical Drug", "1791505"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 0.1 MG/MG Oral Gel  Clinical Drug", "1113433"),
			new CodeableConcept("RxNorm", "doxycycline anhydrous 40 MG Delayed Release Oral Capsule    Clinical Drug", "901399"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Extended Release Enteric Coated Tablet   Clinical Drug ", "577018"),
			new CodeableConcept("RxNorm", "Doxycycline 75 MG Extended Release Enteric Coated Tablet    Clinical Drug ", "577022"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Oral Tablet [Doxycyline]", "540320"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Oral Capsule [Doxycyline]", "540600"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Oral Capsule [Doxycline]", "540598"),
			new CodeableConcept("RxNorm", "Doxycycline 125 MG Enteric Coated Capsule   Clinical Drug ", "347934"),
			new CodeableConcept("RxNorm", "Doxycycline 10 MG/ML Syrup  Clinical Drug ", "198390"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 60 MG Delayed Release Oral Tablet   Clinical Drug", "1801142"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 120 MG Delayed Release Oral Tablet  Clinical Drug", "1801138"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 150 MG Delayed Release Oral Tablet  Clinical Drug", "799048"),
			new CodeableConcept("RxNorm", "Doxycycline 0.1 MG/MG Oral Gel  Clinical Drug ", "797280"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 150 MG Oral Capsule Clinical Drug", "728207"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 75 MG Oral Capsule  Clinical Drug", "700408"),
			new CodeableConcept("RxNorm", "Doxycycline 40 MG Extended Release Capsule  Clinical Drug ", "647109"),
			new CodeableConcept("RxNorm", "Doxycycline 75 MG Extended Release Oral Tablet  Clinical Drug", "602219"),
			new CodeableConcept("RxNorm", "Doxycycline 150 MG Oral Tablet  Clinical Drug ", "597808"),
			new CodeableConcept("RxNorm", "Doxycycline 75 MG Disintegrating Oral Tablet    Clinical Drug", "597521"),
			new CodeableConcept("RxNorm", "Doxycycline Monohydrate 100 MG Disintegrating Oral Tablet   Clinical Drug", "597520"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Extended Release Oral Capsule    Clinical Drug", "578682"),
			new CodeableConcept("RxNorm", "Doxycycline 50 MG Extended Release Oral Tablet  Clinical Drug", "434274"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 100 MG Delayed Release Oral Tablet  Clinical Drug", "434018"),
			new CodeableConcept("RxNorm", "Doxycycline 20 MG/ML Injectable Solution    Clinical Drug", "413721"),
			new CodeableConcept("RxNorm", "Ambroxol 75 MG / Doxycycline 100 MG Extended Release Oral Capsule   Clinical Drug", "411862"),
			new CodeableConcept("RxNorm", "Ambroxol 75 MG / Doxycycline 100 MG Oral Capsule    Clinical Drug", "410896"),
			new CodeableConcept("RxNorm", "Doxycycline 57.7 MG Oral Capsule    Clinical Drug", "410752"),
			new CodeableConcept("RxNorm", "Doxycycline 200 MG Oral Capsule Clinical Drug", "409837"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 75 MG Delayed Release Oral Tablet   Clinical Drug", "406524"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Extended Release Oral Tablet Clinical Drug", "349354"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 75 MG Delayed Release Oral Capsule  Clinical Drug", "348870"),
			new CodeableConcept("RxNorm", "Doxycycline 5 MG/ML Oral Suspension Clinical Drug ", "310030"),
			new CodeableConcept("RxNorm", "Doxycycline 50 MG Oral Tablet   Clinical Drug ", "310029"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 20 MG Oral Capsule  Clinical Drug", "310028"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 100 MG Injection    Clinical Drug", "310027"),
			new CodeableConcept("RxNorm", "Doxycycline Calcium 10 MG/ML Oral Suspension    Clinical Drug", "310026"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Oral Tablet [Doxy-D]", "205617"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Oral Capsule [Doxy-D]", "205603"),
			new CodeableConcept("RxNorm", "Doxycycline 50 MG Oral Capsule [Doxy-D]", "205592"),
			new CodeableConcept("RxNorm", "Doxycycline 50 MG Oral Capsule  Clinical Drug ", "199027"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Oral Capsule Clinical Drug ", "199026"),
			new CodeableConcept("RxNorm", "Doxycycline 10 MG/ML Oral Solution  Clinical Drug ", "755733"),
			new CodeableConcept("RxNorm", "Doxycycline 40 MG Oral Capsule [Oracea]", "643825"),
			new CodeableConcept("RxNorm", "Doxycycline 40 MG Oral Capsule  Clinical Drug ", "643821"),
			new CodeableConcept("RxNorm", "Doxycycline 75 MG Extended Release Oral Capsule Clinical Drug", "578689"),
			new CodeableConcept("RxNorm", "Doxycycline 50 MG Delayed Release Oral Capsule  Clinical Drug", "411887"),
			new CodeableConcept("RxNorm", "Doxycycline 75 MG Oral Tablet   Clinical Drug ", "359465"),
			new CodeableConcept("RxNorm", "Doxycycline 54.4 MG Oral Capsule    Clinical Drug", "349116"),
			new CodeableConcept("RxNorm", "Doxycycline 109 MG Oral Capsule Clinical Drug", "349115"),
			new CodeableConcept("RxNorm", "Doxycycline 109 MG Oral Tablet  Clinical Drug", "349114"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 100 MG Delayed Release Oral Capsule Clinical Drug", "348869"),
			new CodeableConcept("RxNorm", "doxycycline hyclate 20 MG Oral Tablet   Clinical Drug", "283535"),
			new CodeableConcept("RxNorm", "Doxycycline 200 MG Oral Tablet  Clinical Drug", "251843"),
			new CodeableConcept("RxNorm", "Doxycycline 100 MG Oral Tablet  Clinical Drug ", "197633"),
			new CodeableConcept("RxNorm", "Hydrochlorothiazide 12.5 MG / Lisinopril 10 MG Oral Tablet", "197885"),
			new CodeableConcept("RxNorm", "Hydrochlorothiazide 12.5 MG / Lisinopril 20 MG Oral Tablet", "197886"),
			new CodeableConcept("RxNorm", "Hydrochlorothiazide 25 MG / Lisinopril 20 MG Oral Tablet", "197887"),
			new CodeableConcept("RxNorm", "Hydrochlorothiazide 25 MG / Lisinopril 20 MG Oral Tablet [Zestoretic]", "823971"),
			new CodeableConcept("RxNorm", "Hydrochlorothiazide 12.5 MG / Lisinopril 20 MG Oral Tablet [Zestoretic]", "823982"),
			new CodeableConcept("RxNorm", "Hydrochlorothiazide 12.5 MG / Lisinopril 10 MG Oral Tablet [Zestoretic]", "823986"),
			new CodeableConcept("RxNorm", "Lisinopril", "29046"),
			new CodeableConcept("RxNorm", "Lisinopril 40 MG Oral Tablet", "197884"),
			new CodeableConcept("RxNorm", "Lisinopril 30 MG Oral Tablet [Zestril]", "213482"),
			new CodeableConcept("RxNorm", "Lisinopril 2.5 MG Oral Tablet", "311353"),
			new CodeableConcept("RxNorm", "Lisinopril 5 MG Oral Tablet", "311354"),
			new CodeableConcept("RxNorm", "Lisinopril 10 MG", "316151"),
			new CodeableConcept("RxNorm", "Lisinopril 2.5 MG", "316152"),
			new CodeableConcept("RxNorm", "Lisinopril 20 MG", "316153"),
			new CodeableConcept("RxNorm", "Lisinopril 30 MG", "316154"),
			new CodeableConcept("RxNorm", "Lisinopril 40 MG", "316155"),
			new CodeableConcept("RxNorm", "Lisinopril 5 MG", "316156"),
			new CodeableConcept("RxNorm", "Levofloxacin", "82122"),
			new CodeableConcept("RxNorm", "Levofloxacin 250 MG Oral Tablet", "199884"),
			new CodeableConcept("RxNorm", "Levofloxacin 500 MG Oral Tablet", "199885"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML Injectable Solution", "199886"),
			new CodeableConcept("RxNorm", "Levofloxacin 250 MG Oral Tablet [Levaquin]", "InNon-211815"),
			new CodeableConcept("RxNorm", "Levofloxacin 500 MG Oral Tablet [Levaquin]", "211816"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML Injectable Solution [Levaquin]", "211818"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML Injectable Solution", "InNon-242228"),
			new CodeableConcept("RxNorm", "Levofloxacin 750 MG Oral Tablet [Levaquin]", "284481"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML Injectable Solution [Levaquin]", "284487"),
			new CodeableConcept("RxNorm", "Levofloxacin 750 MG Oral Tablet", "311296"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML", "316144"),
			new CodeableConcept("RxNorm", "Levofloxacin 250 MG", "316145"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML", "316146"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML Oral Solution", "477391"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML Oral Solution [Levaquin]", "544445"),
			new CodeableConcept("RxNorm", "Levofloxacin 15 MG/ML", "545117"),
			new CodeableConcept("RxNorm", "Levofloxacin 15 MG/ML Ophthalmic Solution", "545118"),
			new CodeableConcept("RxNorm", "Levofloxacin 15 MG/ML Ophthalmic Solution [Iquix]", "545122"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML [Quixin]", "574876"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML [Levaquin]", "544443"),
			new CodeableConcept("RxNorm", "Levofloxacin 250 MG [Levaquin]", "572148"),
			new CodeableConcept("RxNorm", "Levofloxacin 500 MG [Levaquin]", "572149"),
			new CodeableConcept("RxNorm", "Levofloxacin 750 MG [Levaquin]", "574914"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML [Levaquin]", "574918"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML Ophthalmic Solution [Quixin]", "284440"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML Ophthalmic Solution", "314080"),
			new CodeableConcept("RxNorm", "Levofloxacin 500 MG", "317403"),
			new CodeableConcept("RxNorm", "Levofloxacin 750 MG", "330371"),
			new CodeableConcept("RxNorm", "Levofloxacin 100 MG Oral Tablet", "430645"),
			new CodeableConcept("RxNorm", "Levofloxacin 100 MG", "440774"),
			new CodeableConcept("RxNorm", "Levofloxacin 15 MG/ML [Iquix]", "545120"),
			new CodeableConcept("RxNorm", "Levofloxacin Injectable Product", "1163464"),
			new CodeableConcept("RxNorm", "Levofloxacin Ophthalmic Product", "1163465"),
			new CodeableConcept("RxNorm", "Levofloxacin Oral Liquid Product", "1163466"),
			new CodeableConcept("RxNorm", "Levofloxacin Oral Product", "1163467"),
			new CodeableConcept("RxNorm", "Levofloxacin Pill", "1163468"),
			new CodeableConcept("RxNorm", "Levofloxacin Injectable Solution", "377141"),
			new CodeableConcept("RxNorm", "Levofloxacin Injectable Solution [Levaquin]", "362832"),
			new CodeableConcept("RxNorm", "Levofloxacin Ophthalmic Solution", "376884"),
			new CodeableConcept("RxNorm", "Levofloxacin Ophthalmic Solution [Quixin]", "363748"),
			new CodeableConcept("RxNorm", "Levofloxacin Oral Solution", "477392"),
			new CodeableConcept("RxNorm", "Levofloxacin Oral Tablet", "372588"),
			new CodeableConcept("RxNorm", "Levofloxacin Oral Tablet [Levaquin]", "367638"),
			new CodeableConcept("RxNorm", "Levofloxacin Ophthalmic Solution [Iquix]", "545121"),
			new CodeableConcept("RxNorm", "Levofloxacin Oral Solution [Levaquin]", "544444"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML Injectable Solution", "895915"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML Injectable Solution [Levaquin]", "895916"),
			new CodeableConcept("RxNorm", "levofloxacin anhydrous", "1546009"),
			new CodeableConcept("RxNorm", "Levofloxacin Injection", "Non-1665494"),
			new CodeableConcept("RxNorm", "50 ML Levofloxacin 5 MG/ML Injection", "1665497"),
			new CodeableConcept("RxNorm", "Levofloxacin Injection [Levaquin]", "1665502"),
			new CodeableConcept("RxNorm", "50 ML Levofloxacin 5 MG/ML Injection [Levaquin]", "1665504"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML Injection", "1665505"),
			new CodeableConcept("RxNorm", "Levofloxacin 5 MG/ML Injection [Levaquin]", "1665506"),
			new CodeableConcept("RxNorm", "100 ML Levofloxacin 5 MG/ML Injection", "1665507"),
			new CodeableConcept("RxNorm", "100 ML Levofloxacin 5 MG/ML Injection [Levaquin]", "1665508"),
			new CodeableConcept("RxNorm", "150 ML Levofloxacin 5 MG/ML Injection", "1665515"),
			new CodeableConcept("RxNorm", "150 ML Levofloxacin 5 MG/ML Injection [Levaquin]", "1665516"),
			new CodeableConcept("RxNorm", "20 ML Levofloxacin 25 MG/ML Injection", "1665517"),
			new CodeableConcept("RxNorm", "Levofloxacin 25 MG/ML Injection", "1665518"),
			new CodeableConcept("RxNorm", "30 ML Levofloxacin 25 MG/ML Injection", "1665519")
	};
	
	public static CodeableConcept[][] allCodes = {CT1D,CT1R,CT2L,CT2R,GC1D,GC1R,GC2L};
	public static CodeableConcept[][] diagnosisCodes = {CT1D,GC1D};
	
	public static boolean isSTICode(CodeableConcept code) {
		String sys = code.getsystem();
		if ( "LN".equals(sys) ) {
			sys="LOINC";
		} else
		if ( "SCT".equals(sys) ) {
			sys="SNOMED CT";
		}
		for(CodeableConcept[] codeset : allCodes) {
			for(CodeableConcept possibleCode : codeset) {
				if(code.getcode().equalsIgnoreCase(possibleCode.getcode()) && sys.equalsIgnoreCase(possibleCode.getsystem()) ) {
					return true;
				}
			}
		}
		return false;
	}
	
	public static boolean isSTIDiagnosisCode(CodeableConcept code) {
		String sys = code.getsystem();
		if ( "LN".equals(sys) ) {
			sys="LOINC";
		} else
		if ( "SCT".equals(sys) ) {
			sys="SNOMED CT";
		}
		for(CodeableConcept[] codeset : diagnosisCodes) {
			for(CodeableConcept possibleCode : codeset) {
				if(code.getcode().equalsIgnoreCase(possibleCode.getcode()) && sys.equalsIgnoreCase(possibleCode.getsystem()) ) {
					return true;
				}
			}
		}
		return false;
	}
	
	public static boolean isSTIMed(CodeableConcept code) {
		for(CodeableConcept possibleCode : STIMed) {
			if(code.getcode().equals(possibleCode.getcode()) && code.getsystem().equals(possibleCode.getsystem()) ) {
				return true;
			}
		}
		return false;
	}
}